### ISSUE TITLE
SPI communications not working

### ISSUE THREAD

**Issue by fercuestam** [LieBtrau/arduino-as3933#10]
Hi! Thanks a lot for your work, I've alredy seen you dropped off this project for BLE, however I hope you can help.

I have DemoBoard AS3933.

- Frecuency with manchester pattern generator works perfectly. Modifying the params with official softaware is easy and board wakes up

- SPI communication with AS3933, however does not output the expected results. It gets blocked on the `asTag.begin()` function. After checking code, it reads R5 and R6 for obtaining the default values. In my case, the default value for R6 matches (0x96) but for R5 just reads 0x00. I've tried to read other as R1,R2,R3... but 0x00 is read.

SPI freq comunication is in correct range, wiring is ok - as well as 3V max inputs.
I have oscilloscope to check but does not seem to occur anything strange. 

Something I'll be missing? Do you think of any possible solution?

**Comment by LieBtrau** [comment]
Hi,
It's not easy to figure out what could be wrong.  

You should also check the timings of the SPI-bus (datasheet V1-08, p.32).  Maybe you're clocking the data too fast?

You could also sniff what SPI commands the PIC-microcontroller sends when using the official software.  I suggest you to use a [logic analyzer](https://www.aliexpress.com/item/1005001417581550.html) for that (e.g. with the Saleae software).

Regards,

Christoph

**Comment by fercuestam** [comment]
Hello! Thanks for your help!
Just for closing this issue - I was never been able to communicate with the demo board correctly, instead I went for getting an AS3933 standalone with the componentes and antennas as suggested in the datasheet. Pattern detection works like a charm. Now is the turn of reading data  😨

**Comment by LieBtrau** [comment]
I wish you good luck!
