### ISSUE TITLE
antennaTuning

### ISSUE THREAD

**Issue by konio1** [LieBtrau/arduino-as3933#12]
Hi, I am using your pcb and the same components, how to tune the antenna to 134khz?

**Comment by LieBtrau** [comment]
Hi there, if you want another frequency, you'll have to use another LC-combination.  The datasheet and evaluation kit should give you enough info on how to do that.

**Comment by konio1** [comment]
Thanks for the answer, when I have an xyz antenna can I use one plane (x for example) for 134khz and the other for 125khz?
Regards

**Comment by LieBtrau** [comment]
Hi,
The AS3933 was not designed for detecting two frequencies simultaneously.  You could pull it off, but you would need to set the registers correct for either 125kHz of 134kHz beforehand.  I suggest you try with a single frequency first and build it from that point onwards.

**Comment by konio1** [comment]
Hi,
 I have an antenna tuned to 125khz, the capacitor values ​​are the same as in the datasheet, I want to be able to change the mode from 125khz to 134khz using a button connected to Arduino, I tried to achieve it with "asTag.begin(134000)", but without success, the value I achieve is 128khz according to your function for antenna tuning.
 Regards
