### ISSUE TITLE
Test1 Folder Empty

### ISSUE THREAD

**Issue by rocksyne** [LieBtrau/arduino-as3933#2]
The test 1 file in the example folder is empty, thus an inability to make full use of this great library. Can it please be uploaded? I have been searching for alternatives for months and I will be glad to have your assistance.

Thank you.

**Comment by LieBtrau** [comment]
Hi Rocksyne,
The file was still on a task branch.  I've merged it to the master.

**Comment by rocksyne** [comment]
Thanks a lot for your quick response and kind consideration. I appreciate it a lot. Have a blessed day. ^..^
