### ISSUE TITLE
ASSISTANCE WITH TEST 1 CODE

### ISSUE THREAD

**Issue by rocksyne** [LieBtrau/arduino-as3933#4]
Dear Christoph,
Greeting. Thank you for your assistance the last time. I am sorry I may sound naive on my request below but I will be very grateful if you could please assist me.

Due to hardware wiring constraints, I decided to get the already assembled hardware AS3933 demo board from the manufacturer, as shown in the attachment.

MY REQUEST
---------------------------------
The demo board is able to flicker when a signal is transmitted to it from any 125KHz transmitter. What I want to do is to read signal in binary and display it on my serial monitor connecting it to Arduino in the wiring as shown in your header file documentation.

/* AS3933 functionality
 * Connections:
 * AS3933       ProTrinket 3V
 * 1 [cs]           10
 * 2 [scl]          13
 * 3 [sdi]          11
 * 4 [sdo]          12
 * 5                3V
 * 6                GND
 * 15 [dat]         5
 *
 */

Using, your code, Test 1 specifically, I am able to do the basic configurations. Quite frankly, I am new to embedded systems and a few of the concepts are hard for me to grasp but I am eager to learn.

Please, what do I do? I want to be able to print out the signal in binary representation but I am very lost on where to start from. Please help. My email is rocksyne@gmail.com if you wish to connect with me privately. 

Thank you.

![20170508_222704](https://cloud.githubusercontent.com/assets/925925/25806308/b614c06a-343d-11e7-9caa-e48ff1093c1d.jpg)

**Comment by LieBtrau** [comment]
Hi Rockson,
Before I start doing some charity work, I'd like to know the background of your project.
Is it something you have to do for school?
What's your application?  Hacking car keys?  
What's your background? You say that you are a novice in embedded systems.  Do you have more knowledge of electronics hardware or other relevant topic?

**Comment by rocksyne** [comment]
Hello, Christoph,

Thanks a lot for your response. A quick correction I will like to make. I meant to say I am new at RF devices and their programming. Again, I have been using the Arduino platform for some time now, say 3 years, but because I kept using libraries built by other experienced developers, I never got the opportunity to learn the fundamentals and how they are written [I just use them based on documentations given].

My background is from Compute Engineering. So yes, I have advanced knowledge in electronics and computer systems. However, for several years I had been limited to web application development because of work. I am presently enrolled in my first year of graduate school and I have recently taken that aspect of hardware systems serious because I need the prerequisites to advance in my researches.

Presently I am evaluating some distance bounding protocols in wireless systems operating in the sub-GHz band specifically from 125KHz to 900MHz band.

Like I said, even though I am relatively new to RF, it is an area that excites me very much. I have worked with a few wireless modules which came with enough documentations. However, I noticed there were very little for bands that were lower than 1MHz even though they have a lot of applications.

I hope I have addressed much of what you wanted to know and I will be grateful if you could give me some great insights be it, books, videos,  or any material that has made you such an experienced person in this field. But while I am at it, due to time constraints, I will be very glad if you could please assist me on my request in the previous issue. 

Thanks again for your time.

Regards,
Rockson.

**Comment by LieBtrau** [comment]
Hi Rockson,

To my knowledge there's no distance bounding protocol that is secure.  The problem is that radio waves travel at the speed of light.  The hardware keys for remote access are low power (because you don't want to replace the battery of your car key every day), hence also slow.  Computation speed is nowhere near the speed of light.  An attacker can use much more powerful hardware to get access to your car.  Check google for "relay station attack" or read more [here](https://github.com/LieBtrau/Aiakos/wiki/Security).  Recently on  [Hackaday](https://hackaday.com/2017/04/27/stealing-cars-for-20-bucks/) an attack has been published using low cost hardware.

Regards,

Christoph

**Comment by rocksyne** [comment]
Dear Christoph,

Once again, thanks million for the time you make in replying my messages. Your argument regarding the weaknesses of distance bounding protocols are indeed valid, and really that forms the basis of my research. "How others argue this is a good approach and yet vulnerabilities come up every now and then". 

I have taken a read of the links you gracefully shared and it was an informative read. Thanks once again.

However, regarding my request on how to read data from the AS3933 and display it on my console (serial monitor), I will be grateful if you would please let me know how to go about that too.

As always, I appreciate your time and feedbacks. 

Regards,
Rockson.

**Comment by LieBtrau** [comment]
Hi Rockson,
For converting the data output pulses of the AS3933 to sensible data in your Arduino, you could hack the [IRemote library](https://github.com/z3t0/Arduino-IRremote).  Beware that the Arduino Uno is 5V IO, while the AS3933 is only 3V3.  You'll have to do some voltage level converting.  Use an oscilloscope or logic analyzer to debug.
Regards,
Christoph

**Comment by rocksyne** [comment]
Thank you, Christoph. I truly appreciate your time spent helping me out.

Regards,
Rockson.
