### ISSUE TITLE
I want ask you some questions about it,do you have a email or qq?

### ISSUE THREAD

**Issue by WangYZSC** [LieBtrau/arduino-as3933#6]

**Comment by LieBtrau** [comment]
Hi WangYZSC,
Please post your questions here, so that others may learn from it as well.

**Comment by WangYZSC** [comment]
> Hi WangYZSC,
> Please post your questions here, so that others may learn from it as well.

Thanks a lot.First,I'm a Chinese,my english is not so good ,and I have some problem when reading as3933's datasheet therefore when it doesn't work I'm thinking if there are any initialtion  steps that I missed  and Second I'm not familiar with arduino  do you have a demon on stm32 or nordic 52832

**Comment by LieBtrau** [comment]
Hi WangYZSC,
The code will only run on ATMEGA328P, because of the direct register writes.  I'm not planning to make a port to STM32 or NRF52832.
"It doesn't work" is rather vague.  I can't help you much if you're not specific.

Please tell me about your application.  You might be better off using bluetooth low energy (BLE), e.g. with the nRF52832 if you already have experience with it.

**Comment by WangYZSC** [comment]
> Hi WangYZSC,
> The code will only run on ATMEGA328P, because of the direct register writes. I'm not planning to make a port to STM32 or NRF52832.
> "It doesn't work" is rather vague. I can't help you much if you're not specific.
> 
> Please tell me about your application. You might be better off using bluetooth low energy (BLE), e.g. with the nRF52832 if you already have experience with it.

I config it as the datasheet said ,but when i sending a 125k electromagnetic wave with another mcu it didn't show any response,event the data pin no changs,as the datasheet said when received correct frequency electromagnetic wave no matter the preamble and pattern is correct or wrong,data pin will change to High , i'm confused with it .

**Comment by LieBtrau** [comment]
First try running the calibration routine that is included in the code.  If that works, you can move one step further and use a second device to generate 125KHz and try to detect it.
If your hardware isn't built very well, you'll have trouble calibrating it.  That was my problem also in the beginning.

**Comment by WangYZSC** [comment]
> First try running the calibration routine that is included in the code. If that works, you can move one step further and use a second device to generate 125KHz and try to detect it.
> If your hardware isn't built very well, you'll have trouble calibrating it. That was my problem also in the beginning.

Thanks, at last I fixed it with another Tx devce and Rx device，the problem seems to be a lot ,I didn't calibration it and second， I didn't set the Machester Symbol rate.

**Comment by LieBtrau** [comment]
Take it one step at a time.  If you try to do it all at once you'll make it difficult for yourself to debug.

**Comment by WangYZSC** [comment]
> Take it one step at a time. If you try to do it all at once you'll make it difficult for yourself to debug.

Hi,I met another problem again, after wake-up I read RSSI by SPI ,but after I  used the SPI to read or write , I can not wake-up again,after  I comment the read or write it can work perfectly,do you know what may be the problem?

**Comment by LieBtrau** [comment]
Sorry, I have no clue.

**Comment by WangYZSC** [comment]
> Sorry, I have no clue.

thanks anyway
