### ISSUE TITLE
Wakeup Protocol: Frequency Detection Only

### ISSUE THREAD

**Issue by busyrock** [LieBtrau/arduino-as3933#8]
Dear Christoph,
AS3933 has a wakeup protocol of Frequency Detection Only. 
![image](https://user-images.githubusercontent.com/30133884/100723549-dac43900-33fc-11eb-90de-2b4143010a33.png)
In this section, as3933 should receive data after the Carrier Burst siginal. When the Manchester decoder is enabled (R1<3>=1), the AS3933 decodes the incoming Manchester bits automatically and the Manchester decoded data are displayed on the DAT pin and the Manchester recovered clock on the CL_DAT.
![image](https://user-images.githubusercontent.com/30133884/100724349-bf0d6280-33fd-11eb-8351-3fa861ef70c5.png)
But in practice the CL_DAT PIN does not display recovered clock signal after wakeup. In case a Manchester timing violation happens, the signal on SPO goes high for a duration of 4 periods of internal clock. But I do not find SPO PIN on the AS3933 chip.
Could you give me some advice? Thank you for consultation.

**Comment by LieBtrau** [comment]
Hi Busyrock,
I think it's a typo and should be "SDO".  A search in the datasheet only returns 1 result for "SPO".  The ams.com website seems to be very very slow, so I can't check if there's a new datasheet available.
By the way, I didn't develop the AS3933 solution further.  Bluetooth low energy seemed a much better alternative to me.
